### ISSUE TITLE
Add Repo Name to Message

### ISSUE THREAD

**Issue by Justintime50** [Justintime50/pullbug#16]
# Summary

There is no way to distinguish what repo each PR/MR is from on the reports because the repo name is not included.

## Acceptance Criteria

- [ ] Add the `repo.name` to each message to help distinguish which repo it is.

**Comment by BElluu** [comment]
@Justintime50 I trying do this issue but you done it which discord integration - Nice, you are really fast :D 

Anyway, I'm really newbie so can you give me some feedback to my code? Did I have a good line of thought?
https://github.com/Justintime50/pullbug/pull/20

**Comment by Justintime50** [comment]
@BElluu yeah I can review your PR, as this issue has been addressed in the soon to be merged PR that adds Discord, I'll go ahead and close yours but I'll take a look!

**Comment by BElluu** [comment]
@Justintime50 Thank you so much! :)
