### ISSUE TITLE
Discord integration

### ISSUE THREAD

**Issue by BElluu** [Justintime50/pullbug#17]
Discord has quite a large part of the market.
Integration with this platform could make the application more useful.

**Comment by Justintime50** [comment]
Definitely! I can look into adding this functionality in an upcoming major release. You would be taking advantage of Pullbug via Discord I imagine?

**Comment by BElluu** [comment]
Of course! I using discord with my friends. Getting notification on discord will be awesome. That's better than refresh Gitlab/Github :)

**Comment by Justintime50** [comment]
Merged! v2.1.0 now supports Discord. Let me know if you have troubles.
