### ISSUE TITLE
Extend the operation of pullbug by issues.

### ISSUE THREAD

**Issue by BElluu** [Justintime50/pullbug#19]
I know pullbug description is "Get bugged via Slack or RocketChat to merge your GitHub **pull requests** or GitLab **merge requests**." but what do you think about extend fuctionality by list new issues? That looks perfect for me when on one channel have notification about MRs and on second informations about new issues which testers insert :)

**Comment by Justintime50** [comment]
I like the idea! Doesn't necessarily fit into the name; however, Pullbug could definitely be extended to add issue support.

**Comment by Justintime50** [comment]
Finally coming back to spruce up this repo. I've made a ton of enhancements tonight and will work on adding this in the next couple days to be released in `v3.0.0`.

As a side note, I have removed GitLab support as I know longer use the platform and don't want to maintain it. I noticed in your ask you said `MR` so I can only assume you wanted this functionality specifically for GitLab? If so, it'll only be supported for GitHub as GitLab functionality was removed entirely. You may continue using PullBug > `3.0.0` if you still need GitLab support but it won't include `issues`.

**Comment by Justintime50** [comment]
Issue support added, will be released soon in the next version. Keep an eye on this repo's releases to see when that happens!
